import Head from 'next/head'
import Link from 'next/link'
// import { signIn } from './signIn'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>mahmoud</h1>
      <Link href="/signIn">goo</Link>
    </>
  )
}
