import Head from 'next/head'
// import Link from 'next/link'
import { Sidebar } from '../components/dashboard/Sidebar'
import Content from '../components/dashboard/Content'
// import { signIn } from './signIn'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className="layers">
          <Sidebar />
          <Content />
        </div>
    </>
  )
}
